FROM python:3.12-slim

WORKDIR /usr/app

COPY --from=ghcr.io/astral-sh/uv:0.9.3 /uv /uvx /bin/

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gcc \
    git \
    curl &&\
    rm -rf /var/lib/apt/lists/*

RUN curl https://install.duckdb.org | sh
ENV PATH=/root/.duckdb/cli/latest:${PATH}

COPY ./pyproject.toml ./uv.lock ./

RUN uv venv && \
    uv sync --frozen

COPY . .